services:
  # Web service
  - type: web
    name: smart-coach-web
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x startup.sh
    startCommand: ./startup.sh && gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 10000
      - key: CLOUDAMQP_URL
        fromService:
          name: rabbitmq
          type: pserv
          envVarKey: RABBITMQ_URL
    
  # Background worker for Celery
  - type: worker
    name: smart-coach-worker
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x startup.sh
    startCommand: ./startup.sh && celery -A celery_worker.celery worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: CLOUDAMQP_URL
        fromService:
          name: rabbitmq
          type: pserv
          envVarKey: RABBITMQ_URL

  # RabbitMQ service
  - type: pserv
    name: rabbitmq
    plan: free
    repo: https://github.com/render-examples/rabbitmq
    env: docker
    envVars:
      - key: RABBITMQ_URL
        sync: false